image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-ibank-build-for-testers.jar -P:profile=test &


build_script:
  - chmod +x gradlew # даем права доступа к файлу gradlew
  #  Для selenide headless режим активируется при запуске тестов с параметром: gradlew test -Dselenide.headless=true
  - ./gradlew test -Dselenide.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации